-- MySQL Script generated by MySQL Workbench
-- Mon Sep  7 16:27:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `blog` ;

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `blog` ;

-- -----------------------------------------------------
-- Table `blog`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`comment` ;

CREATE TABLE IF NOT EXISTS `blog`.`comment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` LONGTEXT NOT NULL,
  `isValid` TINYINT(1) NOT NULL,
  `author` INT(11) NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `validation_date` DATETIME NULL DEFAULT NULL,
  `validator` INT(11) NULL DEFAULT NULL,
  `post` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `commentaire_validateur_idx` (`validator` ASC) VISIBLE,
  INDEX `commentaire_auteur_idx` (`author` ASC) VISIBLE,
  INDEX `commentaire_post_idx` (`post` ASC) VISIBLE,
  CONSTRAINT `commentaire_auteur`
    FOREIGN KEY (`author`)
    REFERENCES `blog`.`user` (`id`),
  CONSTRAINT `commentaire_post`
    FOREIGN KEY (`post`)
    REFERENCES `blog`.`post` (`id`),
  CONSTRAINT `commentaire_validateur`
    FOREIGN KEY (`validator`)
    REFERENCES `blog`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blog`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`post` ;

CREATE TABLE IF NOT EXISTS `blog`.`post` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` LONGTEXT NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `author` INT(11) NOT NULL,
  `chapo` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `modification_date` DATETIME NOT NULL,
  `picture` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `post_auteur_idx` (`author` ASC) VISIBLE,
  CONSTRAINT `post_auteur`
    FOREIGN KEY (`author`)
    REFERENCES `blog`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blog`.`token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`token` ;

CREATE TABLE IF NOT EXISTS `blog`.`token` (
  `value` VARCHAR(64) NOT NULL,
  `user` INT(11) NOT NULL,
  `generation_date` DATETIME NOT NULL,
  `expiration_date` DATETIME NOT NULL,
  PRIMARY KEY (`value`),
  UNIQUE INDEX `value_UNIQUE` (`value` ASC) VISIBLE,
  INDEX `token_user_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `token_user`
    FOREIGN KEY (`user`)
    REFERENCES `blog`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `blog`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`user` ;

CREATE TABLE IF NOT EXISTS `blog`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `pseudo` VARCHAR(45) NOT NULL,
  `mail_address` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `active` TINYINT(4) NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `type` INT(11) NOT NULL,
  `modification_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;

USE `blog`;

DELIMITER $$

USE `blog`$$
DROP TRIGGER IF EXISTS `blog`.`comment_BEFORE_INSERT` $$
USE `blog`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `blog`.`comment_BEFORE_INSERT`
BEFORE INSERT ON `blog`.`comment`
FOR EACH ROW
BEGIN
    SET NEW.creation_date := SYSDATE();
END$$


USE `blog`$$
DROP TRIGGER IF EXISTS `blog`.`comment_BEFORE_UPDATE` $$
USE `blog`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `blog`.`comment_BEFORE_UPDATE`
BEFORE UPDATE ON `blog`.`comment`
FOR EACH ROW
BEGIN
	SET NEW.creation_date := OLD.creation_date;
    IF OLD.isvalid = 0 AND NEW.isValid = 1
    THEN
		SET NEW.validation_date := SYSDATE();
    END IF;
END$$


USE `blog`$$
DROP TRIGGER IF EXISTS `blog`.`post_BEFORE_INSERT` $$
USE `blog`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `blog`.`post_BEFORE_INSERT`
BEFORE INSERT ON `blog`.`post`
FOR EACH ROW
BEGIN
    SET NEW.creation_date := SYSDATE();
    SET NEW.modification_date := NEW.creation_date;
END$$


USE `blog`$$
DROP TRIGGER IF EXISTS `blog`.`post_BEFORE_UPDATE` $$
USE `blog`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `blog`.`post_BEFORE_UPDATE`
BEFORE UPDATE ON `blog`.`post`
FOR EACH ROW
BEGIN
	SET NEW.creation_date := OLD.creation_date;
    SET NEW.modification_date := SYSDATE();
END$$


USE `blog`$$
DROP TRIGGER IF EXISTS `blog`.`user_BEFORE_INSERT` $$
USE `blog`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `blog`.`user_BEFORE_INSERT`
BEFORE INSERT ON `blog`.`user`
FOR EACH ROW
BEGIN
	SET NEW.creation_date := SYSDATE();
    SET NEW.modification_date := NEW.creation_date;
    SET NEW.active := 1;
    SET NEW.type := 1;
END$$


USE `blog`$$
DROP TRIGGER IF EXISTS `blog`.`user_BEFORE_UPDATE` $$
USE `blog`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `blog`.`user_BEFORE_UPDATE`
BEFORE UPDATE ON `blog`.`user`
FOR EACH ROW
BEGIN
	SET NEW.creation_date := OLD.creation_date;
    SET NEW.modification_date := SYSDATE();
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
